<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test1" tests="11" skipped="0" failures="6" errors="0" timestamp="2020-03-17T07:18:30" hostname="acer" time="110.915">
  <properties/>
  <testcase name="sendTheMessage" classname="Test1" time="7.988"/>
  <testcase name="sendTheMessage3" classname="Test1" time="2.613">
    <failure message="java.lang.AssertionError: expected [Please enter at least one email address.] but found [Поле не заполнено. Необходимо ввести адрес.]" type="java.lang.AssertionError">java.lang.AssertionError: expected [Please enter at least one email address.] but found [Поле не заполнено. Необходимо ввести адрес.]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at Test1.checkError2_aroundBody28(Test1.java:153)
	at Test1$AjcClosure29.run(Test1.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at Test1.checkError2(Test1.java:150)
	at Test1.sendTheMessage3(Test1.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="sendTheMessage4" classname="Test1" time="1.274">
    <failure message="java.lang.AssertionError: expected [Please enter at least one email address.] but found [Поле не заполнено. Необходимо ввести адрес.]" type="java.lang.AssertionError">java.lang.AssertionError: expected [Please enter at least one email address.] but found [Поле не заполнено. Необходимо ввести адрес.]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at Test1.checkError2_aroundBody28(Test1.java:153)
	at Test1$AjcClosure29.run(Test1.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at Test1.checkError2(Test1.java:150)
	at Test1.sendTheMessage4(Test1.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="sendTheMessage5" classname="Test1" time="4.796"/>
  <testcase name="sendTheMessage6" classname="Test1" time="1.708">
    <failure message="java.lang.AssertionError: expected [Invalid email addresses: djeeeelikyandex.ru] but found [Некорректные адреса: djeeeelikyandex.ru]" type="java.lang.AssertionError">java.lang.AssertionError: expected [Invalid email addresses: djeeeelikyandex.ru] but found [Некорректные адреса: djeeeelikyandex.ru]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at Test1.checkError2_aroundBody28(Test1.java:155)
	at Test1$AjcClosure29.run(Test1.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at Test1.checkError2(Test1.java:150)
	at Test1.sendTheMessage6(Test1.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="sendTheMessage7" classname="Test1" time="2.827">
    <failure message="java.lang.AssertionError: expected [Invalid email addresses: djeeeelik@@yandex.ru] but found [Некорректные адреса: djeeeelik@@yandex.ru]" type="java.lang.AssertionError">java.lang.AssertionError: expected [Invalid email addresses: djeeeelik@@yandex.ru] but found [Некорректные адреса: djeeeelik@@yandex.ru]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at Test1.checkError2_aroundBody28(Test1.java:155)
	at Test1$AjcClosure29.run(Test1.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at Test1.checkError2(Test1.java:150)
	at Test1.sendTheMessage7(Test1.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="languageEng" classname="Test1" time="28.623">
    <failure message="io.qameta.htmlelements.exception.WaitUntilException: язык не выбрался&#10;Expected: element is displayed&#10;     but: element &lt;{name: Кнопка смены языка, так же показывает текущий язык}&gt; is not displayed&#10;Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'&#10;System info: host: 'ACER', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_241'&#10;Driver info: driver.version: unknown" type="io.qameta.htmlelements.exception.WaitUntilException">io.qameta.htmlelements.exception.WaitUntilException: язык не выбрался
Expected: element is displayed
     but: element &lt;{name: Кнопка смены языка, так же показывает текущий язык}&gt; is not displayed
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'ACER', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_241'
Driver info: driver.version: unknown
	at io.qameta.htmlelements.extension.WaitUntilMethod$Extension.handle(WaitUntilMethod.java:31)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$2(WebBlockMethodHandler.java:65)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy25.waitUntil(Unknown Source)
	at Test1.changeLanguage_aroundBody4(Test1.java:77)
	at Test1$AjcClosure5.run(Test1.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at Test1.changeLanguage(Test1.java:72)
	at Test1.languageEng(Test1.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="languageRus" classname="Test1" time="4.511"/>
  <testcase name="activatingCheckboxes" classname="Test1" time="51.268">
    <failure message="io.qameta.htmlelements.exception.WaitUntilException: &#10;Expected: &#10;     but: was &lt;{name: Чекбокcы от меня}&gt;&#10;Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'&#10;System info: host: 'ACER', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_241'&#10;Driver info: driver.version: unknown" type="io.qameta.htmlelements.exception.WaitUntilException">io.qameta.htmlelements.exception.WaitUntilException: 
Expected: 
     but: was &lt;{name: Чекбокcы от меня}&gt;
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'ACER', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_241'
Driver info: driver.version: unknown
	at io.qameta.htmlelements.extension.WaitUntilMethod$Extension.handle(WaitUntilMethod.java:31)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$2(WebBlockMethodHandler.java:65)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy40.waitUntil(Unknown Source)
	at io.qameta.htmlelements.element.ExtendedList.waitUntil(ExtendedList.java:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at io.qameta.htmlelements.extension.DefaultMethod$Extension.handle(DefaultMethod.java:29)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$2(WebBlockMethodHandler.java:65)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy40.waitUntil(Unknown Source)
	at io.qameta.htmlelements.element.ExtendedList.waitUntil(ExtendedList.java:55)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at io.qameta.htmlelements.extension.DefaultMethod$Extension.handle(DefaultMethod.java:29)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$2(WebBlockMethodHandler.java:65)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy40.waitUntil(Unknown Source)
	at Test1.checkActivatingCheckboxes_aroundBody16(Test1.java:116)
	at Test1$AjcClosure17.run(Test1.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at Test1.checkActivatingCheckboxes(Test1.java:115)
	at Test1.activatingCheckboxes(Test1.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="deletingThree" classname="Test1" time="25.264"/>
  <testcase name="deletingTwo" classname="Test1" time="30.725"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
